"""new fields in User model

Revision ID: 41aadc5b4b53
Revises: a865340a2bea
Create Date: 2024-09-23 23:35:27.493284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41aadc5b4b53'
down_revision = 'a865340a2bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
